# Generated by Django 5.1.1 on 2024-10-01 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact"),
                            ("bug_report", "Remontée de bug"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
